ui:
    present: sheet
    layout: two_one
    identifiers:
        master:
            pyui: __default__
        details:
            - name: upper_detail
              pyui: sample_more
              id: key_widget
              title: 'Detail II'
              navigation: False
            - name: lower_detail
              pyui: sample_detail
              id: form_widget
              title: 'Detail Lower'
    detail_items:
        - upper_detail:
            - key_widget:
                - textfield_title
        - lower_detail:
            - form_widget:
                - textview_detail
labels:
    master_list.header.title: 'Config List of Items II'
    master_list.title: 'Master List SDK III'
    master_list.delete.label: 'Erase II'
    main_view.title: 'Config Title for Master-Details SDK II'

